# Generated by Django 5.1.1 on 2024-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('ic_cikgu', models.CharField(max_length=12, unique=True)),
                ('jantina', models.CharField(choices=[('Lelaki', 'Lelaki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('kaum', models.CharField(choices=[('IBAN', 'IBAN'), ('INDO', 'INDO'), ('KADAZAN', 'KADAZAN'), ('KAYAN', 'KAYAN'), ('MELAYU', 'MELAYU'), ('ORANG ASLI', 'ORANG ASLI'), ('SEMAI', 'SEMAI'), ('THAI', 'THAI'), ('LAIN-LAIN', 'LAIN-LAIN')], max_length=50)),
                ('agama', models.CharField(choices=[('BUDDHA', 'BUDDHA'), ('ISLAM', 'ISLAM'), ('KRISTIAN', 'KRISTIAN'), ('TAO', 'TAO'), ('TIADA AGAMA', 'TIADA AGAMA'), ('TERATAI', 'TERATAI'), ('LAIN-LAIN', 'LAIN-LAIN')], max_length=50)),
                ('alamat_rumah', models.CharField(max_length=255)),
                ('pangkat', models.CharField(choices=[('Pengerusi', 'Pengerusi'), ('Naib Pengerusi', 'Naib Pengerusi'), ('Pegawai Ehwal Ekonomi', 'Pegawai Ehwal Ekonomi'), ('Penolong Pegawai Ehwal Ekonomi', 'Penolong Pegawai Ehwal Ekonomi'), ('Juruaudit', 'Juruadti'), ('Penolong Juruaudit', 'Penolong Juruaudit'), ('Lain-lain', 'Lain-lain'), ('Guru Biasa', 'Guru Biasa')], max_length=50)),
                ('ahli', models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=11)),
                ('modal_syer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarikh_daftar', models.DateField()),
            ],
        ),
    ]
