# Generated by Django 5.1.1 on 2024-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pangkat',
            field=models.CharField(choices=[('Pengerusi', 'Pengerusi'), ('Naib Pengerusi', 'Naib Pengerusi'), ('Pegawai Ehwal Ekonomi', 'Pegawai Ehwal Ekonomi'), ('Penolong Pegawai Ehwal Ekonomi', 'Penolong Pegawai Ehwal Ekonomi'), ('Juruaudit', 'Juruadit'), ('Penolong Juruaudit', 'Penolong Juruaudit'), ('Guru Biasa', 'Guru Biasa'), ('Lain-lain', 'Lain-lain')], max_length=50),
        ),
    ]
