# Generated by Django 5.1.1 on 2024-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacher_pangkat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='kaum',
            field=models.CharField(choices=[('IBAN ATAU SEA DAYAK', 'IBAN  ATAU SEA DAYAK'), ('TEMIAR', 'TEMIAR'), ('INDO', 'INDO'), ('KADAZAN', 'KADAZAN'), ('KAYAN', 'KAYAN'), ('MELAYU', 'MELAYU'), ('ORANG ASLI', 'ORANG ASLI'), ('SEMAI', 'SEMAI'), ('THAI', 'THAI'), ('LAIN-LAIN', 'LAIN-LAIN')], max_length=50),
        ),
    ]
