# Generated by Django 5.1.1 on 2024-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_kaum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='kaum',
            field=models.CharField(choices=[('IBAN ATAU SEA DAYAK', 'IBAN  ATAU SEA DAYAK'), ('TEMIAR', 'TEMIAR'), ('INDONESIA', 'INDONESIA'), ('KADAZAN', 'KADAZAN'), ('KAYAN', 'KAYAN'), ('MELAYU', 'MELAYU'), ('ORANG ASLI', 'ORANG ASLI'), ('SEMAI', 'SEMAI'), ('THAI', 'THAI'), ('LAIN-LAIN', 'LAIN-LAIN')], max_length=50),
        ),
    ]
