# Generated by Django 5.1.1 on 2024-11-01 15:38

import django.core.validators
import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_agama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ic_cikgu',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='IC must be exactly 12 digits')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pangkat',
            field=models.CharField(choices=[('Pengerusi', 'Pengerusi'), ('Naib Pengerusi', 'Naib Pengerusi'), ('Pegawai Ehwal Ekonomi', 'Pegawai Ehwal Ekonomi'), ('Penolong Pegawai Ehwal Ekonomi', 'Penolong Pegawai Ehwal Ekonomi'), ('Juruaudit', 'Juruaudit'), ('Penolong Juruaudit', 'Penolong Juruaudit'), ('Guru Biasa', 'Guru Biasa'), ('Lain-lain', 'Lain-lain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=teacher.models.generate_teacher_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
