# Generated by Django 5.1.1 on 2024-11-01 15:44

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_teacher_ic_cikgu_alter_teacher_pangkat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default=teacher.models.generate_teacher_id, editable=False, max_length=9, primary_key=True, serialize=False),
        ),
    ]
