# Generated by Django 5.1.1 on 2024-11-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='agama',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='kaum',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Belum Selesai', 'Belum Selesai')], default='Belum Selesai', max_length=50),
            preserve_default=False,
        ),
    ]
