# Generated by Django 5.1.1 on 2024-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='agama',
        ),
        migrations.RemoveField(
            model_name='member',
            name='kaum',
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Belum Selesai', 'Belum Selesai')], default='Selesai', max_length=50),
            preserve_default=False,
        ),
    ]
