# Generated by Django 5.1.1 on 2024-11-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='student.member'),
        ),
    ]
