# Generated by Django 5.1.1 on 2025-01-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_delete_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tingkatan',
            field=models.CharField(choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50),
        ),
    ]
