# Generated by Django 5.1.1 on 2025-01-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_member_tingkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tingkatan',
            field=models.CharField(choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50),
        ),
    ]
