# Generated by Django 5.1.1 on 2025-01-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_member_tingkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Belum Selesai', 'Belum Selesai')], default='Belum Selesai', max_length=50),
        ),
    ]
