services:
  - type: web
    name: sistem-koperasi-pjays
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn PJayS.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: PJayS.settings
      - key: PYTHON_VERSION
        value: 3.10.13
