# Generated by Django 5.1 on 2024-10-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_alter_teacher_kaum'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahamTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_syer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_saham_added', models.DateField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
