# Generated by Django 5.1 on 2024-10-07 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahamteacher',
            name='modal_syer',
        ),
        migrations.AddField(
            model_name='sahamteacher',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sahamteacher',
            name='date_saham_added',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
