# Generated by Django 5.1 on 2024-10-10 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_remove_sahamteacher_modal_syer_sahamteacher_amount_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_saham_added', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.member')),
            ],
        ),
    ]
