# Generated by Django 5.1 on 2024-11-03 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_sahamstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sahamstudent',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sahamteacher',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sahamstudent',
            name='date_saham_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='sahamteacher',
            name='date_saham_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
